### ISSUE TITLE
Move CMake options to configure the tools in a YAML file

### ISSUE THREAD

**Issue by tristan0x** [BlueBrain/hpc-coding-conventions#128]
# Status

Many variables are defined at CMake level. It makes them a bit complicated to overwrite them (#117), and it is required to run the `configure` phase to use the associated tools (ClangFormat, ...). Furthermore, the CLI utilities are unusable right away since most of their inputs are defined at CMake level.

# Target

* Do not have to run `cmake` to use most of the tools. There are still inherent limits though, for instance:
  * ClangTidy requires:
    * A `compile_commands.json` file (conveniently generated by CMake)
    * All source files to be generated. In NMODL, it means that some make targets must be executed before running the static analysis.
* Centralize the configuration such that it can be exploited by both CMake and the CLI utilities
* Make this configuration easier to maintain and expand

# Proposal

Remove some CMake variables and put them in a new configuration file. hpc-coding-conventions project would provide a default one, but a parent project could provide its own.

## The config file

in YAML format. Filename: `.cppproject.yml`
Default file used by hpc-coding-conventions in `cpp/.cppproject.yml

## List of CMake cache variables to remove

* `${CODING_CONV_PREFIX}_GIT_COMMIT_HOOKS`
* `${CODING_CONV_PREFIX}_GIT_PUSH_HOOKS`
* `${CODING_CONV_PREFIX}_ClangFormat_REQUIRED_VERSION`
* `${CODING_CONV_PREFIX}_ClangFormat_OPTIONS`
* `${CODING_CONV_PREFIX}_ClangFormat_FILES_RE`
* `${CODING_CONV_PREFIX}_ClangFormat_EXCLUDES_RE`
* `${CODING_CONV_PREFIX}_ClangFormat_DEPENDENCIES`
* `${CODING_CONV_PREFIX}_CMakeFormat_REQUIRED_VERSION`
* `${CODING_CONV_PREFIX}_CMakeFormat_OPTIONS`
* `${CODING_CONV_PREFIX}_CMakeFormat_FILES_RE`
* `${CODING_CONV_PREFIX}_CMakeFormat_EXCLUDES_RE`
* `${CODING_CONV_PREFIX}_ClangTidy_REQUIRED_VERSION`
* `${CODING_CONV_PREFIX}_ClangTidy_OPTIONS`
* `${CODING_CONV_PREFIX}_ClangTidy_FILES_RE`
* `${CODING_CONV_PREFIX}_ClangTidy_EXCLUDES_RE`
* `${CODING_CONV_PREFIX}_ClangTidy_DEPENDENCIES`
* `${CODING_CONV_PREFIX}_TEST_FORMATTING`

## Content of the default configuration file

```yaml
tools:

  # a tool is implicitly enabled when specified here

  # not all sections are mandatory, not mentioning a tool means it is not enabled.

  ClangFormat:

    # Any Python version specifiers as described in PEP 440
    # https://peps.python.org/pep-0440/#compatible-release
    # For instance:
    #
    # Exact match required: == 13.0.0
    # At least 13.0.1, but less than 13.1: >= 13.0.1, == 13.0.*
    # Same as above: ~= 13.0.1
    version: ==13.0.0

    # passed to clang-format command line. Can be:
    # - None
    # - a string
    # - a list of string
    option:

    include:
      match:
      - .*\.[it]?cc?$
      - .*\.hh?$
      - .*\.[chit]((pp)|(xx))$

    # targets that needs to be built before formatting the code
    cmake_deps:
    - build_cpp_headers

  CMakeFormat:
    version: ">=0.6, <0.7"
    include:
      match:
      - .*\.cmake$
      - .*CMakeLists.txt$


  ClangTidy:
    # static analysis with ClangTidy is explicitely disabled
    enable: False
    version: ">=7"
    option: -extra-arg=-Wno-unknown-warning-option
    include:
      match: .*\.c((c)|(pp)|(xx))$

  PreCommit:
    enable: False
    hooks:
      commit:
      - check-clang-format
      - check-cmake-format
      push:
      - clang-tidy
      - courtesy-msg

  # Global settings to every tool, can be locally overriden within the
  # section config of a tool

  global:
    exclude:
      match:
      - third[-_]party/.*
      - third[-_]parties/.*
```

### Finding utilities like ClangTidy or CMakeFormat

Using Python version specifiers in the YAML file to describe the versions required is a move toward the idea to create a virtualenv to automagically install the required tools. Right now, the utilities like ClangTidy (an executable) or CMakeFormat (a Python package) are searched by CMake. It is probable that introducing Python version specifiers means the end of this and rely on Python to find (and maybe later install) the required tools.
